[package]
name = "lightningview"
version = "0.4.1"
edition = "2021"
build = "build.rs"

[dependencies]
const_format = "0.2.32"
fltk ={ version = "1.4.25", features = ["fltk-bundled"] }
image = "0.25.0"
[dependencies.imagepipe]
version = "0.5.0"
path = "../imagepipe"
[dependencies.rawler]
version = "0.6.0"
path = "../dnglab/rawler"


[target.'cfg(windows)'.dependencies]
windows = { version = "0.54.0", features = ["Win32_UI_Shell"]}
winreg = "0.52.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
windows = "0.54.0"
