[package]
name = "lightningview"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
const_format = "0.2.32"
fltk ={ version = "1.4.25", features = ["fltk-bundled"] }
imagepipe = "0.5.0"
windows = { version = "0.53.0", features = ["Win32_UI_Shell"]}
winreg = "0.52.0"


[build-dependencies]
winres = "0.1.12"
windows = "0.53.0"

