[package]
name = "lightningview"
version = "1.4.0"
edition = "2021"
build = "build.rs"

[dependencies]
const_format = "0.2.32"
fltk ={ version = "1.4.26", features = ["fltk-bundled"] }
image = "0.25.0"
rand = "0.8.5"
log = "0.4.14"
env_logger = "0.11.3"
arboard = "3.3.2"
[dependencies.imagepipe]
version = "0.5.0"
path = "../imagepipe"
[dependencies.rawler]
version = "0.6.0"
path = "../dnglab/rawler"

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.54.0", features = ["Win32_UI_Shell"]}
winreg = "0.52.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
windows = "0.54.0"
