[package]
name = "lightningview"
version = "0.3.1"
edition = "2021"
build = "build.rs"

[dependencies]
const_format = "0.2.32"
fltk ={ version = "1.4.25", features = ["fltk-bundled"] }
image = "0.24.9"
imagepipe = "0.5.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.53.0", features = ["Win32_UI_Shell"]}
winreg = "0.52.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
windows = "0.53.0"
